import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navber/Navber";
import { ThemeProvider } from "@/components/ThemeProvider/ThemeProvider";
import Footer from "@/components/Footer/Footer";
import { Toaster } from 'react-hot-toast'; // ১. ইম্পোর্ট করুন

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LumenSoft - Tech Solutions",
  description: "Generated by LumenSoft",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        
        <ThemeProvider>
         
          <Toaster 
            position="top-center" 
            reverseOrder={false} 
            toastOptions={{
              
              style: {
                background: '#333',
                color: '#fff',
                borderRadius: '10px',
              },
            }}
          />
          
          <Navbar />
          <main className="min-h-[80vh]">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}